---
title: "Lab 10"
author: "Samantha Kuglen"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(usethis)

library(beepr)
library(praise)
library(cowsay)
library(paletteer)
library(sf)
```

## beepr:: beep()

Use `beep()` to give yourself an audio alert

## for loop + beep 

```{r, eval = FALSE}
for (i in rev(seq(1:99))) {
  print(paste(i, "bottles of beer on the wall"))
}

beep(4)
```


## praise is nice :-)
```{r}
praise("${EXCLAMATION} !!! This code works ${adverb_manner}!")

praise("Holy ${creating}, Batman - this code works ${ADVERB_MANNER}!")
```

## cowsay::say to have characters say something

```{r}
say("I love tacos!", by = 'trilobite')
```

## usethis for everything

R project first, then git & Github repo.

- usethis::use_git() for version control local repo
- usethis:use_github() to create an upstream repo and connect to it

## paletteer: aggregated color palettes
```{r}
storms %>% 
  group_by(name) %>% 
  summarize(min_pressure = min(pressure, na.rm = TRUE)) %>% 
  slice_min(n = 10, min_pressure) %>% 
  ggplot(aes(x = min_pressure, y = name)) +
    geom_col(aes(fill = name)) + 
    scale_fill_paletteer_d("trekcolors::lcars_cardassian") # pkg::palette 

    #paletteerr_d("palettetown::volbeat") in console to get hex value for individual colors from palette
```

